#!/usr/bin/perl -T
# $Id: diff,v 1.31 2013/01/11 14:43:47 ajlittoz Exp $

# diff --	Display diff output with markup.
#
#	Arne Georg Gleditsch <argggh@ifi.uio.no>
#	Per Kristian Gjermshus <pergj@ifi.uio.no>
#
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

######################################################################

$CVSID = '$Id: diff,v 1.31 2013/01/11 14:43:47 ajlittoz Exp $ ';

#use strict;
use lib do { $0 =~ m{(.*)/} ? "$1/lib" : "lib" }; # if LXR modules are in ./lib

use LXR::Common;
use LXR::Markup;
use LXR::Template;
use Local;
use FileHandle;
@docxygen=("","","","","","","linux-3.5.4","x86_32","real","doxygen","http://124.16.141.179/lxr/lxr-code/source/linux-3.5.4/","http://124.16.141.179/doxygen_kernel/linux-3.5.4/html/files.html","linux-3.5.4","x86_64","real","doxygen","http://124.16.141.179/lxr/lxr-code/source/linux-3.5.4/","http://124.16.141.179/doxygen_kernel/linux-3.5.4/html/files.html","linux-3.19.8","x86_32","real","doxygen","http://124.16.141.179/lxr/lxr-code/source/linux-3.19.8/","http://124.16.141.179/doxygen_kernel/linux-3.19.8/html/files.html","linux-3.19.8","x86_64","real","doxygen","http://124.16.141.179/lxr/lxr-code/source/linux-3.19.8/","http://124.16.141.179/doxygen_kernel/linux-3.19.8/html/files.html"
);
$length=@docxygen;

sub watchlist{   
     
print("<form memethod=get action=\"watchlist\"> <input type=\"hidden\" name=\"v\" value=\"",$ENV{'QUERY_STRINGSID'},"\">");
print("<input type=\"hidden\" name=\"f\" value=\"",$ENV{'QUERY_STRINGFID'},"\">");
print("<input type=\"hidden\" name=\"a\" value=\"",$ENV{'QUERY_STRINGPID'},"\">");
print("Path0: <input type=text name=\"path0\" ","value=\"",$path0,"\" size=20 >\n");
print("Path1: <input type=text name=\"path1\" ","value=\"",$path1,"\" size=20 >\n");
#print("<input type=\"checkbox\" name=\"checkbox1\" value=\"1\" $checked> zoom\n");
print("<input type=submit value=\"function list\">\n","</form>\n");
#$sid=$ENV{'QUERY_STRINGSID'};
#$pid=$ENV{'QUERY_STRINGPID'};
#   if ($che1 ne "checkbox") {$c1=t0;}     else {$c1=t1;}
if ($path0 ne "" || $path1 ne "")
#if($checked eq "1")
{
#system("/home/hwei/./test-twd.rb");
  if($path0 ne "")
  {
     if ($path0 eq "*")
     {
        $path00=sprintf("root");
      }
      else
      {
        $path00=$path0;
      } 
  }
  else
  {
       $path00=sprintf("NULL");
  }
  if($path1 ne "")
  {
     if ($path1 eq "*")
     {
        $path11=sprintf("root");
     }
     else
     {
        $path11=$path1;
     }
  }
  else
  {
     $path11=sprintf("NULL");
  }
#print("/home/hwei/./callgraph-perl".$sid.$pid.$path00.$path11.$c1."/home/hwei/lxr/source1 /home/hwei/".$config->baseurl."/home/hwei/lxr/source1");
   (my $url = $config->baseurl) =~ s!/*$!/!;

        $url =~ s/([\?\&\;\=\'\"])/sprintf('%%%02x',(unpack('c',$1)))/ge;

#$ttbasurl=$config->baseurl;
   $ttbasurl=sprintf("http://124.16.141.179/lxr");

   
   $docxygen_flag=0;
   for($i=0;$i<$length;$i+=6){
        if(($docxygen[$i] eq $ver_v)&&($docxygen[$i+1] eq $ver_a)&&($docxygen[$i+2] eq $ver_f) )
        {
              if($docxygen[$i+3] eq "docxygen")
             {
                $docxygen_flag=1;
             }
             else
             {
                $docxygen_flag=0;
             }
             $code_url=$docxygen[$i+4];
             $note_url=$docxygen[$i+5];
             break;
        }
   }

   $temp_sh=$config->sourceroot;
	#puts $temp_sh
   $temp_shrb=$temp_sh;
   $temp_shrb=~s/source\//lxr\/.\/watchfuc-perl/;
   $temp_shsp=$temp_sh;
   $temp_shsp=~s/source/lxr\/source1/;
   $temp_shy=$temp_sh;
   $temp_shy=~s/source/lxr\//;
#print($temp_shrb." ".$ENV{'QUERY_STRINGSID'}."  ".$ENV{'QUERY_STRINGPID'}."  ".$ENV{'QUERY_STRINGFID'}."  ".$path00."  ".$path11."  ".$temp_shsp."  ".$temp_shy."  ".$ttbasurl."  ".$temp_shsp." ".$code_url." ".$docxygen_flag." ".$note_url);
system("$temp_shrb $ver_v $ver_a $ver_f $path00 $path11 $temp_shsp $temp_shy $ttbasurl $temp_shsp $code_url $docxygen_flag $note_url");
#system("/home/hwei/lxr/./callgraph-perl  $ENV{'QUERY_STRINGSID'} $ENV{'QUERY_STRINGPID'}  $path00 $path11 $c1 /home/hwei/lxr/source1 /home/hwei/ $url /home/hwei/lxr/source1");
#print($ttbasurl);
# system("/home/hwei/lxr/./temptest  $ttbasurl  xxxx");
#print("/home/hwei/./callgraph-perl".$ENV{QUERY_STRINGSID}.$ENV{'QUERY_STRINGPID'}."kk".$path00."kk".$path11."kk".$c1."kk"." /home/hwei/lxr/source1 /home/hwei/".$config->baseurl."/home/hwei/lxr/source1");
}

}
httpinit;

=begin
if (!$ENV{'QUERY_STRINGSID'} || !$ENV{'QUERY_STRINGPID'} || !$ENV{'QUERY_STRINGFID'})   #add from 20150605 by jdi -- default argvs
{
                $ver_v="linux-3.5.4";
                $ver_a="x86_32";
                $ver_f="real";
}
=cut
if (!$ENV{'QUERY_STRINGFID'})   #add from 20150609 by jdi -- default argvs
{
                $ver_v=$ENV{'QUERY_STRINGSID'};
                $ver_a=$ENV{'QUERY_STRINGPID'};
                $ver_f="real";
}
else
{
	$ver_v=$ENV{'QUERY_STRINGSID'};
	$ver_a=$ENV{'QUERY_STRINGPID'};
	$ver_f=$ENV{'QUERY_STRINGFID'};
}
$path0 =$HTTP->{'param'}->{'path0'};
$path1 =$HTTP->{'param'}->{'path1'};
$sid=$HTTP->{'param'}->{'v'};
makeheader('watchlist');
&watchlist;
makefooter('watchlist');

httpclean;
